// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALhprlNkvGQzC94LN2iDrS7hX00K78Yjg',
    appId: '1:846682976739:web:5f2858f6db39accc6ff0d6',
    messagingSenderId: '846682976739',
    projectId: 'signin-example-38945',
    authDomain: 'signin-example-38945.firebaseapp.com',
    databaseURL: 'https://signin-example-38945-default-rtdb.firebaseio.com',
    storageBucket: 'signin-example-38945.appspot.com',
    measurementId: 'G-2H5GT0S3Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTDZK-00mzO2dCYALsLGHjUHjGi6WGPU',
    appId: '1:846682976739:android:3594145349d22e296ff0d6',
    messagingSenderId: '846682976739',
    projectId: 'signin-example-38945',
    databaseURL: 'https://signin-example-38945-default-rtdb.firebaseio.com',
    storageBucket: 'signin-example-38945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0GqWq0EVR_K8nDUB8d88z8N1FAfkcCp8',
    appId: '1:846682976739:ios:89a3acfa8fc34eb26ff0d6',
    messagingSenderId: '846682976739',
    projectId: 'signin-example-38945',
    databaseURL: 'https://signin-example-38945-default-rtdb.firebaseio.com',
    storageBucket: 'signin-example-38945.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0GqWq0EVR_K8nDUB8d88z8N1FAfkcCp8',
    appId: '1:846682976739:ios:89a3acfa8fc34eb26ff0d6',
    messagingSenderId: '846682976739',
    projectId: 'signin-example-38945',
    databaseURL: 'https://signin-example-38945-default-rtdb.firebaseio.com',
    storageBucket: 'signin-example-38945.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALhprlNkvGQzC94LN2iDrS7hX00K78Yjg',
    appId: '1:846682976739:web:89d1a950432ac8486ff0d6',
    messagingSenderId: '846682976739',
    projectId: 'signin-example-38945',
    authDomain: 'signin-example-38945.firebaseapp.com',
    databaseURL: 'https://signin-example-38945-default-rtdb.firebaseio.com',
    storageBucket: 'signin-example-38945.appspot.com',
    measurementId: 'G-4VK87KVH1F',
  );
}
